version: '3.8'

services:
  app:
    image: shopping-spring
    container_name: shopping-spring
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/shopping
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - backend

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: shopping
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d  # 📌 SQL 스크립트 실행 경로
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
